# Generated by Django 2.1.7 on 2021-10-26 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211026_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 26, 16, 14, 35, 334226)),
        ),
    ]
